### ISSUE TITLE
Roadmap for Nitro

### ISSUE THREAD

**Issue by dan-jan** [janhq/nitro#192]
## Short-term Roadmap

Nitro is a tiny (5mb) local, multi-modal AI engine that can replace OpenAI's API. 
- https://github.com/janhq/nitro/issues/175#185 
- Expose `/chat/completions` and automagically handle load/unload/run operations
- `/models` folder by convention/configuration

To consider:
- API Keys

## Tasks

- [ ] Hiro's proposal (Nitro's eventual path as an embeddable AGI) at the framework layer?
- [ ] Clear Architecture for Jan on how we integrate difference "Inference Engines" (e.g. Nvidia TensorRT stack)

![image](https://github.com/janhq/nitro/assets/101145494/3240e1c0-2185-469c-bdc3-166e1c9f8a66)

**Comment by 0xSage** [comment]
More wishlist items: 
- Nitro CLI
- Nitro client libraries

**Comment by tikikun** [comment]
> More wishlist items:
> 
> * Nitro CLI
> * Nitro client libraries

- Nitro CLI and nitro client libraries should be contained inside one single distribution

**Comment by tikikun** [comment]
- Model management specs

https://github.com/janhq/nitro/issues/195

**Comment by tikikun** [comment]
> Current december plan:
> 
> * Multiple loading models (but still single run model) https://hackmd.io/kQO3XWdJSP2fRZpjyfw6Hg
>   
>   * Can resolve multiple issues when integrating with apps (@0xSage @louis-jan ux issues)
> * Differentiation between load and run a model
>   
>   * Can resolve multiple issues when integrating with apps (@0xSage @louis-jan ux issues)
> * Vision
>   
>   * Feature parity with OpenAI
> * Speech to text model
>   
>   * Feature parity with OpenAI
> * Text to speech and images model (low chance of success since the text to speech and images model is not having popularity in cpp yet)

this is up for discussion

**Comment by tikikun** [comment]
Summary:
- Nitro CLI and Nitro Client
  + Should be combined into one single distribution on each platform (npm pip brew...)
- Multiple loading models (but still single run model) https://hackmd.io/kQO3XWdJSP2fRZpjyfw6Hg
  + Can resolve multiple issues when integrating with apps (@0xSage @louis-jan ux issues)
- Differentiation between load and run a model
  + Can resolve multiple issues when integrating with apps (@0xSage @louis-jan ux issues)
- Vision
  + Feature parity with OpenAI
- Speech to text model
  + Feature parity with OpenAI
- Text to speech and images model (low chance of success since the text to speech and images model is not having popularity in cpp yet)

Reference issues list
https://github.com/janhq/nitro/issues/195
https://github.com/janhq/nitro/issues/104
https://github.com/janhq/nitro/issues/103

**Comment by dan-jan** [comment]
Cross-platform

**Comment by 0xSage** [comment]
See roadmap: https://github.com/orgs/janhq/projects/5/views/12
